# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20170408_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
