# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_parkingspot_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
