# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_parkingspot_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
